### ISSUE TITLE
IPTV Simple Client issue

### ISSUE THREAD

**Issue by KarelDeBruine** [braz96/skin.mimic#61]
Hey Braz96, using latest Mimic version on Kodi Krypton there is a bug on IPTV.

When clicking LIVE TV (channels) it shows my channel list as usual, but when choosing a channel the channel list disappears.

And it's actually ugly, so could you also direct some attention to the Live Tv tab and make it both beautiful and functional like the rest of your skin?

Love your work been using your skin for the start, keep it up!

Thank you either way.

**Comment by braz96** [comment]
You're going to need to post a screenshot, the LiveTV section should already look like the rest of the skin.

**Comment by KarelDeBruine** [comment]
Okay little genius, i will do so once i sober up 😂.
And i also have a "discrete request/idea" which i will post once i'll send
you the screenshots.

But for now, i wish you and your loved ones a happy new year without
hardships or worries.

Enjoy!
Op 29-dec.-2016 18:20 schreef "braz96" <notifications@github.com>:

**Comment by Asparta** [comment]
I have this issue too on my android and windows devices, braz i have to firstly say that your skin mimic not omni is the best looking and customisable skin for kodi! No question!
So thank you, i will prove my support is you accept by donations.
BUT, it's true my pvr doesnt show channels. I mean it does show channels but once i select a channel and then go 1 step back to the pvr home menu the list is black.

I came here today because i thought you would have fixed it by this latest update 5.0.3 but it's not fixed.

I did notice that you have fixed the play/pause button remaining on it's place as a starting point which was also an issue for me.

Should i post a video or screenshots about the pvr issue?

**Comment by braz96** [comment]
What pvr backed are you using? Does it work in other skin's? Doesn't sound like a skin issue, more likely an issue with your pvr addon.

**Comment by Asparta** [comment]
I'm using Android devices, latest release of kodi krypton.
The pvr works great on Estuary, Confluence etc..
But not on Mimic.
It is definitly a Mimic problem.

I have done a completely New installation of Kodi and Mimic but the problem
remains.

**Comment by Asparta** [comment]
I'm using the PVR Simple Client.

**Comment by braz96** [comment]
You'll need to post a video or screenshots, pvr works fine with other clients.

**Comment by jimmyal08** [comment]
Hi braz96, I'm having this issue too. When you open your Channels the list opens normally, then when you select a channel it starts minimized but everything else turns black and the channels list goes away. Screenshots links below:

Before selecting a Channel:
https://www.dropbox.com/s/urzyudaremb5ek5/Before.png?dl=1

After selecting a Channel:
https://www.dropbox.com/s/05xq28v2uitmo2f/After.png?dl=1

If it doesn't work by pressing the links, copy and paste them.

I also noticed that even though the channels list goes away when playback is minimized, if you press where the list should be it selects other channels. So apparently the list stays there working, it is just hidden or something.

**Comment by braz96** [comment]
What is the source for your channels, is it even legal?

There are no visibility conditions on the channel list, are you sure it works OK in other skin's. Sounds like it might be related to Kodi's recent caching changes, not sure though.

**Comment by jimmyal08** [comment]
I tried in confluence and it works, not the way is supposed to, but works. I also tried in Aeon Nox and Estuary and it didn't work. Also tried with my own paid suscription to check if it was because of the source of the channels and the same happened too. So it may be something related to Kodi or the Simple Client and not your skin. Sorry for that. Either way, if you find something regarding that matter please let me know. By the way, not sure if it is correct to ask this here, but what happened with the option to always show the submenu in the horizontal menu layout?

As a side note, amazing creation your mimic skin, I really like it. Is the best skin in my opinion. Simple, but yet powerful.

**Comment by braz96** [comment]
@jimmyal08 With the home screen redesign, it's no longer possible to display the main menu and submenu at the same time.

**Comment by pistikas** [comment]
Hi braz96,

I have the same problem, please, check this [video](https://youtu.be/o9kJN9O2nB4).
Where` there could be a problem? Waiting for your comments...Thanks

**Comment by braz96** [comment]
Sounds like it happens in other skin's too and is not a Mimic issue. Other PVR add-ons work fine here. Likely nothing I can do unless you can show me that there is a specific issue with the skin code.

**Comment by pistikas** [comment]
What other PVR add-ons work fine? And maybe you know where to report about this bug?

**Comment by jimmyal08** [comment]
I'm not sure if you guys solved this issue or found a workaround for it, but just in case for the benefit of everyone this is what worked for me.

Go to Settings>Player>Videos and turn off the 2 Allow Hardware Acceleration.

 At least for me, after doing that, everything worked perfectly. I hope it can help you guys.

**Comment by Asparta** [comment]
Indeed turning hardware accelleration off solves the error, but some
channels now don't show an image anymore only sound! But the hell with
those channels, Braz i gotta say your skin is the best kodi skin ever
created! KODI would suck without your skins! 16 was okay but unstable, but
17 is much, MUCH better.

So i'm sure that you did your best and i've seen your updates through 17
without errors probably because you are a barbarian (perfectionist, real,
sharing, caring, straight foreward, humane and defensive when needed) so
the error that we see is definitly on de Kodi developers.

I want to expres my gratitude for your efforts and say that i enjoy your
skin!

You are the best skinner of the whole kodi enterprise, this includes
confluence and estuary!

If you ever want to stop doing this nonsense, please inspire a young soul
to learn how to code.

If you have a paypal or anything else i will gladly support you or atleast
donate a little something for your efforts.

Big respect, the Moroccan!

Op 21 mrt. 2017 23:05 schreef "jimmyal08" <notifications@github.com>:
