### ISSUE TITLE
When installing from zip -Addon doesn't display.

### ISSUE THREAD

**Issue by codechik** [braz96/skin.mimic#70]
Hello: Just wanted to make you aware of one or two issues I've had when working with the skin thusfar. After installing a zip, addon enabled doesn't pop up on the screen. And the other was while working with the skin, it had a complete breakdown to blank sections where as I could no longer make changes. I had to wipe the system and reinstall everything. Didn't save the log file tho.

**Comment by braz96** [comment]
Not much I can do with limited info and no logs. The first issue isn't skin related. If you manually extract the zip, you need to then enable it in the add-on info dialog. If you're installing it via the add-on browser, then it's likely some other issue but not due to the skin.

I can only guess that the other issue is that the main menu isn't showing up. If the skin is properly installed it will automatically install script.skinshortcuts for the menus.

**Comment by codechik** [comment]
I had to reinstall the skin altogether. That 1st issue was weird tho, I could not configure alot of my addons. Only run or uninstall, or get the log info.

**Comment by codechik** [comment]
Oh and I'm sorry, I am working with Jarvis still. I have alot of people who don't want Krypton yet. I'm about to make something for that as well. I would like to continue using this mimic skin. I enjoy it.

**Comment by braz96** [comment]
Sounds like you're making a build for distribution, that isn't something I can provide support for.

**Comment by codechik** [comment]
No, no I have a build that I give to my family. We have a closed system and everyone like the Jarvis.

**Comment by braz96** [comment]
No paid version and mimic 5 already has widget defaults for the local libraries. I don't support builds though, or widgets for particular add-ons.

**Comment by codechik** [comment]
Oh, does it? Mimic 5, isn't that for Krypton? Or can I use it for Jarvis also? If that's the case, that will work fine....
Thanks so much for your assistance. I'll geton that Mimic 5 and see what I can do.

**Comment by braz96** [comment]
Mimic 5 is for Krypton only.
